major bug fixes; preventing unset variables

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -18,10 +18,10 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-version="Generate (gen) version: 1.3.3 - December 2, 2022"
+version="Generate (gen) version: 1.3.4 - December 3, 2022"
 
-template_check() {
-    if [[ -f "${template_file}" ]]; then
+get_template() {
+    if [[ -f "${template_file:-}" ]]; then
         template="$(< "${template_file}")"
         format="templates"
 
@@ -48,7 +48,6 @@ cat << EOF
 #!/usr/bin/env perl
 use strict;
 use warnings;
-
 EOF
 }
 
@@ -67,7 +66,6 @@ EOF
 gen_sh() {
 cat << EOF
 #!/usr/bin/env ${ext}
-
 EOF
 }
 
@@ -133,8 +131,18 @@ launch_ed() {
 }
 
 echo_text() {
-    template_check
+    get_template
     gen_"${format:-sh}" >> "${filename}"
+}
+
+create_file() {
+    if [[ -e "$filename" ]]; then
+        printf "Filename already exists.\n"; exit 1
+    else
+        if ! touch "$filename" 2> /dev/null; then
+            printf "Failed to create %s.\n" "$filename"; exit 1
+        fi
+    fi
 }
 
 check_ext() {
@@ -149,18 +157,8 @@ check_ext() {
         *js) exe=true; ext="node" ;;
         *py) exe=true; format="py" ;;
         *pl) exe=true; format="pl" ;;
-        *) [[ ! -f "${template_file}" ]] && quiet=true ;;
+        *) [[ ! -f "${template_file:-}" ]] && quiet=true ;;
     esac
-}
-
-create_file() {
-    if [[ -e "$filename" ]]; then
-        printf "Filename already exists.\n"; exit 1
-    else
-        if ! touch "$filename" 2> /dev/null; then
-            printf "Failed to create %s.\n" "$filename"; exit 1
-        fi
-    fi
 }
 
 get_args() {
@@ -178,18 +176,31 @@ get_args() {
     done
 }
 
+check_template() {
+    if [[ -n "${ext}" ]]; then
+        [[ -f "${HOME}/.gen/templates/template.${ext}" ]] && \
+            template_file="${HOME}/.gen/templates/template.${ext}"
+    fi
+}
+
+get_ext() {
+    case "${filename}" in
+        *.*) ext="${filename##*.}" ;;
+        *) ext=""
+    esac
+}
+
 main() {
     filename="${!#}"
     basename="${filename##*/}"
-    [[ -n "${filename##*.}" ]] && ext="${filename##*.}"
-    [[ -f "${HOME}/.gen/templates/template.${ext}" ]] && \
-        template_file="${HOME}/.gen/templates/template.${ext}"
+    get_ext
+    check_template
     get_args "$@"
-    create_file
     check_ext
-    [[ "${exe}" ]] && chmod u+x "${filename}"
-    [[ ! "${quiet}" ]] && echo_text
-    [[ ! "${suppress}" ]] && launch_ed
+    create_file
+    [[ "${exe:-}" ]] && chmod u+x "${filename}"
+    [[ ! "${quiet:-}" ]] && echo_text
+    [[ ! "${suppress:-}" ]] && launch_ed
 }
 
 if [[ "$#" -eq 0 ]]; then
