clarify environmental variables

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -21,8 +21,8 @@
 version="Generate (gen) version: 1.3.3 - December 2, 2022"
 
 template_check() {
-    if [[ -f "${TEMPLATE_FILE}" ]]; then
-        template="$(< "${TEMPLATE_FILE}")"
+    if [[ -f "${template_file}" ]]; then
+        template="$(< "${template_file}")"
         format="templates"
 
 gen_templates() {
@@ -66,7 +66,7 @@ EOF
 
 gen_sh() {
 cat << EOF
-#!/usr/bin/env ${EXT}
+#!/usr/bin/env ${ext}
 
 EOF
 }
@@ -93,14 +93,14 @@ gen_jsx() {
 cat << EOF
 import React from 'react';
 
-function ${BASENAME%.*}() {
+function ${basename%.*}() {
   return (
     <>
     </>
   );
 }
 
-export default ${BASENAME%.*};
+export default ${basename%.*};
 EOF
 }
     fi
@@ -126,7 +126,7 @@ exit 0
 }
 
 launch_ed() {
-    if ! "${EDITOR:-vi}" "${FILENAME}" 2> /dev/null; then
+    if ! "${EDITOR:-vi}" "${filename}" 2> /dev/null; then
         printf "Failed to launch editor.\n"
         printf "Try 'gen -h' for more information.\n"; exit 1
     fi
@@ -134,44 +134,44 @@ launch_ed() {
 
 echo_text() {
     template_check
-    gen_"${format:-sh}" >> "${FILENAME}"
+    gen_"${format:-sh}" >> "${filename}"
 }
 
 check_ext() {
-    case "$EXT" in
+    case "$ext" in
         *awk) exe=true ;;
         *ksh) exe=true ;;
         *csh) exe=true ;;
         *c) format="c" ;;
         *jsx) format="jsx" ;;
         *html|*htm) format="html" ;;
-        *sh) exe=true; EXT="bash" ;;
-        *js) exe=true; EXT="node" ;;
+        *sh) exe=true; ext="bash" ;;
+        *js) exe=true; ext="node" ;;
         *py) exe=true; format="py" ;;
         *pl) exe=true; format="pl" ;;
-        *) [[ ! -f "${TEMPLATE_FILE}" ]] && quiet=true ;;
+        *) [[ ! -f "${template_file}" ]] && quiet=true ;;
     esac
 }
 
 create_file() {
-    if [[ -e "$FILENAME" ]]; then
+    if [[ -e "$filename" ]]; then
         printf "Filename already exists.\n"; exit 1
     else
-        if ! touch "$FILENAME" 2> /dev/null; then
-            printf "Failed to create %s.\n" "$FILENAME"; exit 1
+        if ! touch "$filename" 2> /dev/null; then
+            printf "Failed to create %s.\n" "$filename"; exit 1
         fi
     fi
 }
 
 get_args() {
-    while getopts 'xqse:dvh' OPTION; do
-        case "$OPTION" in
+    while getopts 'xqse:dvh' option; do
+        case "$option" in
             h) usage ;;
             x) exe=true ;;
             q) quiet=true ;;
             s) suppress=true ;;
             e) EDITOR="$OPTARG" ;;
-            d) unset TEMPLATE_FILE ;;
+            d) unset template_file ;;
             v) printf "%s\n" "$version"; exit 0 ;;
             ?) printf "Try 'gen -h' for more information.\n"; exit 1 ;;
         esac
@@ -179,15 +179,15 @@ get_args() {
 }
 
 main() {
-    FILENAME="${!#}"
-    BASENAME="${FILENAME##*/}"
-    [[ -n "${FILENAME##*.}" ]] && EXT="${FILENAME##*.}"
-    [[ -f "${HOME}/.gen/templates/template.${EXT}" ]] && \
-        TEMPLATE_FILE="${HOME}/.gen/templates/template.${EXT}"
+    filename="${!#}"
+    basename="${filename##*/}"
+    [[ -n "${filename##*.}" ]] && ext="${filename##*.}"
+    [[ -f "${HOME}/.gen/templates/template.${ext}" ]] && \
+        template_file="${HOME}/.gen/templates/template.${ext}"
     get_args "$@"
     create_file
     check_ext
-    [[ "${exe}" ]] && chmod u+x "${FILENAME}"
+    [[ "${exe}" ]] && chmod u+x "${filename}"
     [[ ! "${quiet}" ]] && echo_text
     [[ ! "${suppress}" ]] && launch_ed
 }
