made `exists` exit erroneously

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -104,7 +104,7 @@ Generate FILE, auto-input typical text, and auto-launch default editor.
 Full documentation <https://github.com/membersincewayback/gen>
 ${version}
 EOF
-exit
+exit $1
 }
 
 check_ext() {
@@ -124,10 +124,11 @@ check_ext() {
 
 exists() {
     if [[ -e "$FILENAME" ]]; then
-        printf "Filename already exists.\n"; exit
+        printf "Filename already exists.\n"; exit 1
     else
         if ! touch "$FILENAME" 2> /dev/null; then
-            usage
+            printf "Error: Couldn't touch \"$FILENAME\"\n\n" 
+            usage 1
         fi
     fi
 }
