clean main func; add exe to python

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -18,7 +18,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-version="Generate (gen) version: 1.3.2 - December 2, 2022"
+version="Generate (gen) version: 1.3.3 - December 2, 2022"
 
 template_check() {
     if [[ -f "${TEMPLATE_FILE}" ]]; then
@@ -35,6 +35,7 @@ ${template}
 
 gen_py() {
 cat << EOF
+#!/usr/bin/env python
 def main():
 
 if __name__ == '__main__':
@@ -44,7 +45,7 @@ EOF
 
 gen_pl() {
 cat << EOF
-#!/usr/bin/perl
+#!/usr/bin/env perl
 use strict;
 use warnings;
 
@@ -114,7 +115,7 @@ Generate FILE, auto-input typical text, and auto-launch default editor.
   -q,   quiet auto-input of script template
   -s,   suppress auto-launch of editor
   -e,   select editor ( gen -e nano test.txt )
-  -d,   force default template when custom available
+  -d,   force default template despite available custom
   -v,   display version number and exit
   -h,   display this help and exit
 
@@ -124,18 +125,30 @@ EOF
 exit 0
 }
 
+launch_ed() {
+    if ! "${EDITOR:-vi}" "${FILENAME}" 2> /dev/null; then
+        printf "Failed to launch editor.\n"
+        printf "Try 'gen -h' for more information.\n"; exit 1
+    fi
+}
+
+echo_text() {
+    template_check
+    gen_"${format:-sh}" >> "${FILENAME}"
+}
+
 check_ext() {
     case "$EXT" in
         *awk) exe=true ;;
         *ksh) exe=true ;;
         *csh) exe=true ;;
         *c) format="c" ;;
-        *py) format="py" ;;
         *jsx) format="jsx" ;;
         *html|*htm) format="html" ;;
         *sh) exe=true; EXT="bash" ;;
-        *pl) exe=true; format="pl" ;;
         *js) exe=true; EXT="node" ;;
+        *py) exe=true; format="py" ;;
+        *pl) exe=true; format="pl" ;;
         *) [[ ! -f "${TEMPLATE_FILE}" ]] && quiet=true ;;
     esac
 }
@@ -153,13 +166,13 @@ create_file() {
 get_args() {
     while getopts 'xqse:dvh' OPTION; do
         case "$OPTION" in
+            h) usage ;;
             x) exe=true ;;
             q) quiet=true ;;
             s) suppress=true ;;
             e) EDITOR="$OPTARG" ;;
             d) unset TEMPLATE_FILE ;;
             v) printf "%s\n" "$version"; exit 0 ;;
-            h) usage ;;
             ?) printf "Try 'gen -h' for more information.\n"; exit 1 ;;
         esac
     done
@@ -175,13 +188,8 @@ main() {
     create_file
     check_ext
     [[ "${exe}" ]] && chmod u+x "${FILENAME}"
-    [[ ! "${quiet}" ]] && \
-        template_check && gen_"${format:-sh}" >> "${FILENAME}"
-    [[ ! "${suppress}" ]] && \
-        if ! "${EDITOR:-vi}" "${FILENAME}" 2> /dev/null; then
-            printf "Failed to launch editor.\n"
-            printf "Try 'gen -h' for more information.\n"; exit 1
-        fi
+    [[ ! "${quiet}" ]] && echo_text
+    [[ ! "${suppress}" ]] && launch_ed
 }
 
 if [[ "$#" -eq 0 ]]; then
