make all tabbing match

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -32,7 +32,7 @@ gen_py() {
 	def main():
 
 	if __name__ == '__main__':
-		main()
+	    main()
 	EOF
 }
 
@@ -43,7 +43,7 @@ gen_c() {
 
 	int main() {
 
-		return 0;
+	    return 0;
 	}
 	EOF
 }
@@ -74,7 +74,7 @@ gen_html() {
 }
 
 gen_jsx() {
-    basename="${filename##*/}"
+	basename="${filename##*/}"
 	cat <<-EOF
 	import React from 'react';
 
@@ -111,120 +111,120 @@ usage() {
 }
 
 which_ed() {
-    if which "${VISUAL:-}" &> /dev/null; then
-        editor="$VISUAL"
-    elif which "${EDITOR:-}" &> /dev/null; then
-        editor="$EDITOR"
-    else
-        editors=( nano vi ed )
-        for ed in "${editors[@]}"; do
-            editor="$(which "$ed" &> /dev/null)" && return
-        done
-    fi
+	if which "${VISUAL:-}" &> /dev/null; then
+		editor="$VISUAL"
+	elif which "${EDITOR:-}" &> /dev/null; then
+		editor="$EDITOR"
+	else
+		editors=( nano vi ed )
+		for ed in "${editors[@]}"; do
+			editor="$(which "$ed" &> /dev/null)" && return
+		done
+	fi
 }
 
 create_one() {
-    if [[ -e "$filename" ]]; then
-        printf "gen: file '%s' already exists.\n" "$filename"; exit 1
-    else
-        if ! touch "$filename" 2> /dev/null; then
-            printf "gen: cannot generate '%s': Permission denied\n" "$filename"; exit 1
-        fi
-    fi
+	if [[ -e "$filename" ]]; then
+		printf "gen: file '%s' already exists.\n" "$filename"; exit 1
+	else
+		if ! touch "$filename" 2> /dev/null; then
+			printf "gen: cannot generate '%s': Permission denied\n" "$filename"; exit 1
+		fi
+	fi
 }
 
 create_multi() {
-    for ((i=1; i <= multi; i++)); do
-        if [[ -n "${ext:-}" ]]; then
-            new="${filename%.*}${i}.${filename##*.}"
-        else
-            new="${filename}${i}"
-        fi
-        if [[ -e "$new" ]]; then
-            printf "gen: file '%s' already exists.\n" "$new"; exit 1
-        else
-            if ! touch "$new" 2> /dev/null; then
-                printf "gen: cannot generate '%s': Permission denied\n" "$filename"; exit 1
-            fi
-        fi
-        [[ -n "${mode:-}" ]] && chmod "${mode}" "$new"
-        [[ -z "${quiet:-}" ]] && gen_"${format:-sh}" >> "$new"
-    done
-    exit 0
+	for ((i=1; i <= multi; i++)); do
+		if [[ -n "${ext:-}" ]]; then
+			new="${filename%.*}${i}.${filename##*.}"
+		else
+			new="${filename}${i}"
+		fi
+		if [[ -e "$new" ]]; then
+			printf "gen: file '%s' already exists.\n" "$new"; exit 1
+		else
+			if ! touch "$new" 2> /dev/null; then
+				printf "gen: cannot generate '%s': Permission denied\n" "$filename"; exit 1
+			fi
+		fi
+		[[ -n "${mode:-}" ]] && chmod "${mode}" "$new"
+		[[ -z "${quiet:-}" ]] && gen_"${format:-sh}" >> "$new"
+	done
+	exit 0
 }
 
 check_ext() {
-    case "${ext:-}" in
-        awk) mode="u+x" ;;
-        c) format="c" ;;
-        jsx) format="jsx" ;;
-        html|htm) format="html" ;;
-        js) mode="u+x"; ext="node" ;;
-        pl) mode="u+x"; ext="perl" ;;
-        py) mode="u+x"; format="py" ;;
-        sh|bash) mode="u+x"; ext="bash" ;;
-        *sh) mode="u+x" ;;
-        *)
-            if [[ -n "${template:-}" ]]; then
-                format="templates"
-            else
-                quiet=true
-            fi
-        ;;
-    esac
+	case "${ext:-}" in
+		awk) mode="u+x" ;;
+		c) format="c" ;;
+		jsx) format="jsx" ;;
+		html|htm) format="html" ;;
+		js) mode="u+x"; ext="node" ;;
+		pl) mode="u+x"; ext="perl" ;;
+		py) mode="u+x"; format="py" ;;
+		sh|bash) mode="u+x"; ext="bash" ;;
+		*sh) mode="u+x" ;;
+		*)
+			if [[ -n "${template:-}" ]]; then
+				format="templates"
+			else
+				quiet=true
+			fi
+		;;
+	esac
 }
 
 get_template() {
-    [[ -f "$HOME/.gen/templates/template.$ext" ]] && \
-        template="$(< "$HOME/.gen/templates/template.$ext")"
+	[[ -f "$HOME/.gen/templates/template.$ext" ]] && \
+		template="$(< "$HOME/.gen/templates/template.$ext")"
 }
 
 get_args() {
-    while getopts ':hxqdsc:ve:m:' option; do
-        case "$option" in
-            h) usage ;;
-            x) mode="u+x" ;;
-            q) quiet=true ;;
-            d) default=true ;;
-            s) suppress=true ;;
-            c) mode="$OPTARG" ;;
-            v) printf "%s\n" "$version"; exit 0 ;;
-            e) if which "$OPTARG" &> /dev/null; then editor="$OPTARG"; fi ;;
-            m)
-                if [[ "$OPTARG" =~ ^[0-9]*$ ]]; then
-                    multi="$OPTARG"; suppress=true
-                else
-                    printf "gen: Provide a positive integer to generate multiple files.\n"
-                    printf "Try 'gen -h' for more information.\n"; exit 1
-                fi
-            ;;
+	while getopts ':hxqdsc:ve:m:' option; do
+		case "$option" in
+			h) usage ;;
+			x) mode="u+x" ;;
+			q) quiet=true ;;
+			d) default=true ;;
+			s) suppress=true ;;
+			c) mode="$OPTARG" ;;
+			v) printf "%s\n" "$version"; exit 0 ;;
+			e) if which "$OPTARG" &> /dev/null; then editor="$OPTARG"; fi ;;
+			m)
+				if [[ "$OPTARG" =~ ^[0-9]*$ ]]; then
+					multi="$OPTARG"; suppress=true
+				else
+					printf "gen: Provide a positive integer to generate multiple files.\n"
+					printf "Try 'gen -h' for more information.\n"; exit 1
+				fi
+			;;
 
-            ?)
-                printf "gen: invalid option -- '%s'\n" "$OPTARG"
-                printf "Try 'gen -h' for more information.\n"; exit 1
-            ;;
-        esac
-    done
-    shift "$((OPTIND -1))"
-    if [[ -n "${1:-}" ]]; then
-        filename="$1"
-    else
-        printf "gen: Must provide filename.\n"
-        printf "Try 'gen -h' for more information.\n"; exit 1
-    fi
+			?)
+				printf "gen: invalid option -- '%s'\n" "$OPTARG"
+				printf "Try 'gen -h' for more information.\n"; exit 1
+			;;
+		esac
+	done
+	shift "$((OPTIND -1))"
+	if [[ -n "${1:-}" ]]; then
+		filename="$1"
+	else
+		printf "gen: Must provide filename.\n"
+		printf "Try 'gen -h' for more information.\n"; exit 1
+	fi
 }
 
 main() {
-    get_args "$@"
-    [[ "${filename}" == *.* ]] && ext="${filename##*.}"
-    [[ -z "${default:-}" && -n "${ext:-}" ]] && get_template
-    check_ext
-    [[ -n "${multi:-}" ]] && create_multi
-    create_one
-    [[ -n "${mode:-}" ]] && chmod "${mode}" "$filename"
-    [[ -z "${quiet:-}" ]] && gen_"${format:-sh}" >> "$filename"
-    [[ -z "${suppress:-}" && -z "${editor:-}" ]] && which_ed
-    [[ -z "${suppress:-}" ]] && "$editor" "$filename"
+	get_args "$@"
+	[[ "${filename}" == *.* ]] && ext="${filename##*.}"
+	[[ -z "${default:-}" && -n "${ext:-}" ]] && get_template
+	check_ext
+	[[ -n "${multi:-}" ]] && create_multi
+	create_one
+	[[ -n "${mode:-}" ]] && chmod "${mode}" "$filename"
+	[[ -z "${quiet:-}" ]] && gen_"${format:-sh}" >> "$filename"
+	[[ -z "${suppress:-}" && -z "${editor:-}" ]] && which_ed
+	[[ -z "${suppress:-}" ]] && "$editor" "$filename"
 }
 
 main "$@"
